# Generated by Django 4.2 on 2023-10-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_product_price_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cprice',
            new_name='price',
        ),
    ]
