# Generated by Django 4.2 on 2023-10-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_image_product_image1_product_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='category',
        ),
    ]
